name: Build, Test and Deploy LI\ibrary App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Change the backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start the Backend
      run: npm run start-be &
    - name: Start the Frontend
      run: npm run start-fe &
    - name: Execute the UI tests
      run: npm run test

  deploy-be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_BE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

  deploy-fe:
    runs-on: ubuntu-latest
    needs: deploy-be
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_FE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true